
SERVER_TWO_INTERVAL_CHECKING = 2
SERVER_ONE_INTERVAL_CHECKING = 2
MESSAGE_PING_ERROR = "STOP"

LOG_FILENAME = "../files/servers.log"

COLOR_ERROR = "red bold"
COLOR_SERVER_ONE = "green"
COLOR_SERVER_TWO = "cyan"

SERVER_ONE_IP = "localhost"
SERVER_ONE_CLIENT_IP = "localhost"
SERVER_TWO_CLIENT_IP = "localhost"
SERVER_TWO_IP = "localhost"

SERVER_ONE_PORT = 2223
SERVER_ONE_CLIENT_PORT = 2222
SERVER_TWO_CLIENT_PORT = 2225
SERVER_TWO_PORT = 2224

